export const TOP_CURRENCIES = [
  { code: 'USD', flag: '🇺🇸', label: 'US Dollar', symbol: '$' },
  { code: 'EUR', flag: '🇪🇺', label: 'Euro', symbol: '€' },
  { code: 'GBP', flag: '🇬🇧', label: 'British Pound', symbol: '£' },
  { code: 'RUB', flag: '🇷🇺', label: 'Russian Ruble', symbol: '₽' },
  { code: 'BYN', flag: '🇧🇾', label: 'Belarusian Ruble', symbol: 'Br' },
  { code: 'KZT', flag: '🇰🇿', label: 'Kazakhstani Tenge', symbol: '₸' },
  { code: 'AED', flag: '🇦🇪', label: 'UAE Dirham', symbol: 'DH' },
  { code: 'CAD', flag: '🇨🇦', label: 'Canadian Dollar', symbol: 'CA$' },
  { code: 'AUD', flag: '🇦🇺', label: 'Australian Dollar', symbol: 'A$' },
  { code: 'SGD', flag: '🇸🇬', label: 'Singapore Dollar', symbol: 'S$' },
  { code: 'HKD', flag: '🇭🇰', label: 'Hong Kong Dollar', symbol: 'HK$' },
  { code: 'TRY', flag: '🇹🇷', label: 'Turkish Lira', symbol: '₺' },
  { code: 'CNY', flag: '🇨🇳', label: 'Chinese Yuan', symbol: '¥' },
  { code: 'JPY', flag: '🇯🇵', label: 'Japanese Yen', symbol: '¥' },
];
