version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    restart: unless-stopped
    volumes:
      - backend_data:/app/.data
    # Здесь мы мапим внешний порт 18082 на внутренний 8000
    ports:
      - "18082:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "18080:80"

volumes:
  backend_data: