services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: kwikmenu
      POSTGRES_USER: kwikmenu
      POSTGRES_PASSWORD: kwikmenu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - backend_data:/app/.data
    # Здесь мы мапим внешний порт 18082 на внутренний 8000
    ports:
      - "18082:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "18080:80"

volumes:
  backend_data:
  postgres_data:
