"""add_email_campaigns"""

revision = 'a847f74479c6'
down_revision = 'b6bac85c9de3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_campaign_steps',
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('delay_hours', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('condition_rule', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_campaign_steps'))
    )
    op.create_table('scheduled_emails',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('unisender_message_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['email_campaign_steps.id'], name=op.f('fk_scheduled_emails_step_id_email_campaign_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scheduled_emails_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_emails'))
    )
    op.create_index(op.f('ix_scheduled_emails_step_id'), 'scheduled_emails', ['step_id'], unique=False)
    op.create_index(op.f('ix_scheduled_emails_unisender_message_id'), 'scheduled_emails', ['unisender_message_id'], unique=True)
    op.create_index(op.f('ix_scheduled_emails_user_id'), 'scheduled_emails', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_emails_user_id'), table_name='scheduled_emails')
    op.drop_index(op.f('ix_scheduled_emails_unisender_message_id'), table_name='scheduled_emails')
    op.drop_index(op.f('ix_scheduled_emails_step_id'), table_name='scheduled_emails')
    op.drop_table('scheduled_emails')
    op.drop_table('email_campaign_steps')
    # ### end Alembic commands ###
